### ISSUE TITLE
Runaway persistant mob buffs.

### ISSUE THREAD

**Issue by mactso** [Traverse-Joe/tuff-depth#2]
Hi, the mod is causing runaway stat buffs for persistent mobs that don't despawn.

I suggest you try "public void onCheckSpawnerSpawn(LivingSpawnEvent.CheckSpawn event)" instead of the Enter World Event.   

You can look at Harder Farther to see how it's coded there.

Good Luck!  
Cheers.
MacTso

**Comment by Tokerot** [comment]
Can confirm, i ended up with endermen that had 20k hp, initially thought it was a bug with harder father but after talking to mactso he found the issue was tuff depth stacking buffs repeatedly. since endermen don't despawn when holding items they were the ones i noticed getting crazy buffs, but its possible it affects other persistent mobs

**Comment by mactso** [comment]
Was going over issues and saw I hadn't updated this one.  We did look into this bug and it was being caused by Tuff Depths at the time.

I retested this and can't duplicate the problem with harder spawners and harder farther.

I'm adding your suggestion "I suggest you try "public void onCheckSpawnerSpawn(LivingSpawnEvent.CheckSpawn event)" instead of the Enter World Event." to the modding discord channel.  I'll be updating HarderSpawners to 1.19.1 and will test/analyze how that works.
